# SPDX-License-Identifier: GPL-3.0-or-later

wifi_ssid: "your-wifi-ssid"
wifi_password: "your-wifi-password"
ap_password: "choose-an-access-point-password"
marax__encryption_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
